"""Iter61 · Phase C — Driver Salary & Payment Ledger.

Two collections:
  * driver_salary_masters  — effective-dated salary versions per driver
  * driver_ledger_entries  — the immutable transaction log:
      credit  = amount OWED to driver (salary earned)
      debit   = amount PAID / DEDUCTED (advance, trip recovery, settlement)
    Balance = Σ(credit) − Σ(debit).  Positive => we still owe the driver.

Entry types  (kept as a bounded whitelist for reporting integrity):
   salary            — credit; auto-generated by post-monthly-salary
   advance           — debit ; salary advance paid mid-month
   other_payment     — debit ; any other outflow to driver
   trip_recovery     — debit ; auto-mirrored from Trip driver_recovery
   other_deduction   — debit ; manual deduction (uniform, damages, ...)
   settlement        — debit ; monthly close-out payment

Every row is scoped by (user_id, company_id, driver_id) so multi-company
isolation is enforced by construction.  Trip-linked rows carry
`reference = {"kind":"trip","id":<tid>}` so we can idempotently upsert /
delete when Trips change (Trip = single source of truth).
"""
from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import datetime, timezone, date
import io, csv

from db import db
from auth import get_current_user
from company import _active_company_id
from models import new_id
from audit import _log_audit

router = APIRouter(prefix="/api")

# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------
EntryType = Literal[
    "salary", "advance", "other_payment",
    "trip_recovery", "other_deduction", "settlement",
]
_CREDIT_TYPES = {"salary"}
_DEBIT_TYPES = {"advance", "other_payment", "trip_recovery", "other_deduction", "settlement"}
_MANUAL_TYPES = {"salary", "advance", "other_payment", "other_deduction"}


class SalaryMasterIn(BaseModel):
    monthly_salary: float = Field(..., ge=0)
    effective_from: str = Field(..., min_length=10, max_length=10)
    effective_to: Optional[str] = None
    remarks: Optional[str] = None


class LedgerEntryIn(BaseModel):
    entry_date: str = Field(..., min_length=10, max_length=10)
    entry_type: EntryType
    amount: float = Field(..., gt=0)
    remarks: Optional[str] = None


class SettleIn(BaseModel):
    month: str = Field(..., min_length=7, max_length=7)  # YYYY-MM
    paid_amount: float = Field(..., ge=0)
    remarks: Optional[str] = None


class PostMonthlySalaryIn(BaseModel):
    month: str = Field(..., min_length=7, max_length=7)


def _month_key(d: str) -> str:
    return (d or "")[:7]


async def _assert_driver(user_id: str, cid: str, did: str) -> dict:
    drv = await db.drivers.find_one(
        {"id": did, "user_id": user_id, "company_id": cid},
        {"_id": 0, "user_id": 0},
    )
    if not drv:
        raise HTTPException(status_code=404, detail="Driver not found")
    return drv


# ===========================================================================
# Salary Master CRUD
# ===========================================================================
@router.get("/drivers/{did}/salary-masters")
async def list_salary_masters(did: str, request: Request, user=Depends(get_current_user)):
    cid = await _active_company_id(request, user)
    await _assert_driver(user["user_id"], cid, did)
    docs = await (db.driver_salary_masters
                  .find({"user_id": user["user_id"], "company_id": cid, "driver_id": did}, {"_id": 0})
                  .sort([("effective_from", -1), ("version", -1)])
                  .to_list(500))
    return {"items": docs}


@router.post("/drivers/{did}/salary-masters")
async def create_salary_master(did: str, payload: SalaryMasterIn, request: Request,
                                user=Depends(get_current_user)):
    """Create a new effective-dated salary record.

    Historical records are NEVER edited — creating a new record with a
    later effective_from date supersedes prior salary starting from that
    date.  Prior record's `effective_to` is auto-set to
    (new.effective_from - 1 day) IF it was open-ended.
    """
    cid = await _active_company_id(request, user)
    await _assert_driver(user["user_id"], cid, did)
    now = datetime.now(timezone.utc).isoformat()
    # Close out any open-ended prior salary that overlaps
    prior = await db.driver_salary_masters.find_one(
        {"user_id": user["user_id"], "company_id": cid, "driver_id": did,
         "$or": [{"effective_to": None}, {"effective_to": {"$exists": False}}],
         "effective_from": {"$lt": payload.effective_from}},
        sort=[("effective_from", -1)],
    )
    if prior:
        # yesterday of new.effective_from
        try:
            y = datetime.strptime(payload.effective_from, "%Y-%m-%d").date()
            eff_to = (y.replace(day=y.day)).isoformat() if y.day == 1 else ""
            from datetime import timedelta as _td
            eff_to = (y - _td(days=1)).isoformat()
        except Exception:
            eff_to = payload.effective_from
        await db.driver_salary_masters.update_one(
            {"id": prior["id"]},
            {"$set": {"effective_to": eff_to, "updated_at": now, "updated_by": user["user_id"]}},
        )
    # Version = count of prior records + 1
    prev_count = await db.driver_salary_masters.count_documents(
        {"user_id": user["user_id"], "company_id": cid, "driver_id": did}
    )
    doc = {
        "id": new_id("dsm"),
        "user_id": user["user_id"], "company_id": cid, "driver_id": did,
        "version": prev_count + 1,
        "monthly_salary": float(payload.monthly_salary),
        "effective_from": payload.effective_from,
        "effective_to": payload.effective_to or None,
        "remarks": (payload.remarks or "").strip() or None,
        "created_at": now, "created_by": user["user_id"],
        "updated_at": now, "updated_by": user["user_id"],
    }
    await db.driver_salary_masters.insert_one(doc)
    doc.pop("_id", None)
    await _log_audit(user, "driver_salary_master", "create", entity_id=doc["id"], entity_ref=did)
    return doc


async def _resolve_salary_master_for_month(user_id: str, cid: str, did: str, month: str) -> Optional[dict]:
    """Return the salary master that applies to the last day of `month`
    (YYYY-MM).  Used by monthly-salary posting."""
    # Compute the last date of the month
    from calendar import monthrange
    y, m = int(month[:4]), int(month[5:7])
    last_day = f"{month}-{monthrange(y, m)[1]:02d}"
    p = await db.driver_salary_masters.find_one(
        {"user_id": user_id, "company_id": cid, "driver_id": did,
         "effective_from": {"$lte": last_day},
         "$or": [
             {"effective_to": {"$exists": False}},
             {"effective_to": None},
             {"effective_to": {"$gte": last_day}},
         ]},
        sort=[("effective_from", -1), ("version", -1)],
    )
    if p:
        p.pop("_id", None)
    return p


# ===========================================================================
# Ledger CRUD
# ===========================================================================
async def _serialize_entry(e: dict) -> dict:
    e.pop("_id", None); e.pop("user_id", None)
    return e


async def _list_entries(user_id: str, cid: str, did: str,
                        date_from: str = "", date_to: str = "") -> list:
    q = {"user_id": user_id, "company_id": cid, "driver_id": did}
    if date_from or date_to:
        rng: dict = {}
        if date_from: rng["$gte"] = date_from
        if date_to: rng["$lte"] = date_to
        q["entry_date"] = rng
    docs = await (db.driver_ledger_entries.find(q, {"_id": 0, "user_id": 0})
                  .sort([("entry_date", 1), ("created_at", 1)])
                  .to_list(5000))
    return docs


def _compute_running_balance(entries: list, opening_balance: float = 0.0) -> tuple:
    """Return (entries-with-balance, closing_balance, credit_sum, debit_sum)."""
    bal = float(opening_balance or 0.0)
    credit_sum = debit_sum = 0.0
    out = []
    for e in entries:
        amt = float(e.get("amount", 0) or 0)
        if e.get("direction") == "credit":
            bal += amt
            credit_sum += amt
        else:
            bal -= amt
            debit_sum += amt
        out.append({**e, "balance": round(bal, 2)})
    return out, round(bal, 2), round(credit_sum, 2), round(debit_sum, 2)


async def _compute_opening_balance(user_id: str, cid: str, did: str, before_date: str) -> float:
    """Sum credit-debit for all entries strictly BEFORE the given date."""
    if not before_date:
        return 0.0
    pipeline = [
        {"$match": {
            "user_id": user_id, "company_id": cid, "driver_id": did,
            "entry_date": {"$lt": before_date},
        }},
        {"$group": {
            "_id": "$direction",
            "total": {"$sum": "$amount"},
        }},
    ]
    result = {r["_id"]: float(r["total"]) async for r in db.driver_ledger_entries.aggregate(pipeline)}
    return round(result.get("credit", 0.0) - result.get("debit", 0.0), 2)


@router.get("/drivers/{did}/ledger")
async def list_ledger(did: str, request: Request, user=Depends(get_current_user),
                      date_from: str = "", date_to: str = ""):
    """Return ledger for the driver in the given window with
    opening + closing balance and per-row running balance.
    """
    cid = await _active_company_id(request, user)
    drv = await _assert_driver(user["user_id"], cid, did)
    opening = await _compute_opening_balance(user["user_id"], cid, did, date_from) if date_from else 0.0
    entries = await _list_entries(user["user_id"], cid, did, date_from, date_to)
    entries_with_bal, closing, credit_sum, debit_sum = _compute_running_balance(entries, opening)
    return {
        "driver": {"id": drv["id"], "name": drv["name"], "phone": drv.get("phone")},
        "opening_balance": opening,
        "closing_balance": closing,
        "credit_total": credit_sum,
        "debit_total": debit_sum,
        "entries": entries_with_bal,
        "date_from": date_from or None,
        "date_to": date_to or None,
    }


@router.post("/drivers/{did}/ledger")
async def create_ledger_entry(did: str, payload: LedgerEntryIn, request: Request,
                               user=Depends(get_current_user)):
    """Manually add a ledger entry (salary, advance, other_payment,
    other_deduction).  System-generated types (trip_recovery, settlement)
    cannot be posted through this endpoint — use the dedicated endpoints."""
    cid = await _active_company_id(request, user)
    await _assert_driver(user["user_id"], cid, did)
    if payload.entry_type not in _MANUAL_TYPES:
        raise HTTPException(
            status_code=400,
            detail=f"entry_type '{payload.entry_type}' is not manually postable — use the dedicated endpoint",
        )
    direction = "credit" if payload.entry_type in _CREDIT_TYPES else "debit"
    now = datetime.now(timezone.utc).isoformat()
    doc = {
        "id": new_id("dle"),
        "user_id": user["user_id"], "company_id": cid, "driver_id": did,
        "entry_date": payload.entry_date,
        "month_key": _month_key(payload.entry_date),
        "entry_type": payload.entry_type,
        "direction": direction,
        "amount": round(float(payload.amount), 2),
        "source": "manual",
        "remarks": (payload.remarks or "").strip() or None,
        "reference": None,
        "created_at": now, "created_by": user["user_id"],
        "updated_at": now, "updated_by": user["user_id"],
    }
    await db.driver_ledger_entries.insert_one(doc)
    doc.pop("_id", None); doc.pop("user_id", None)
    await _log_audit(user, "driver_ledger", "create", entity_id=doc["id"], entity_ref=did,
                     changes={"entry_type": payload.entry_type, "amount": payload.amount})
    return doc


@router.delete("/drivers/{did}/ledger/{eid}")
async def delete_ledger_entry(did: str, eid: str, request: Request,
                               user=Depends(get_current_user)):
    """Delete a manually-created ledger entry.  Trip-linked or
    system-generated entries cannot be deleted this way — they follow
    the source Trip (single source of truth)."""
    cid = await _active_company_id(request, user)
    existing = await db.driver_ledger_entries.find_one(
        {"id": eid, "user_id": user["user_id"], "company_id": cid, "driver_id": did},
    )
    if not existing:
        raise HTTPException(status_code=404, detail="Ledger entry not found")
    if existing.get("source") != "manual":
        raise HTTPException(
            status_code=400,
            detail="System-generated entries cannot be deleted directly. Edit the source Trip instead.",
        )
    await db.driver_ledger_entries.delete_one({"id": eid, "user_id": user["user_id"], "company_id": cid})
    await _log_audit(user, "driver_ledger", "delete", entity_id=eid, entity_ref=did,
                     changes={"snapshot": {k: existing.get(k) for k in ("entry_date", "entry_type", "amount")}})
    return {"ok": True}


@router.post("/drivers/{did}/ledger/post-monthly-salary")
async def post_monthly_salary(did: str, payload: PostMonthlySalaryIn, request: Request,
                               user=Depends(get_current_user)):
    """Generate the monthly salary credit for the given month.
    Idempotent — re-posting the same month updates the amount to the
    current salary master value.  Historic months keep the salary that
    was effective THEN (via resolve_salary_master_for_month).
    """
    cid = await _active_company_id(request, user)
    drv = await _assert_driver(user["user_id"], cid, did)
    month = payload.month
    if len(month) != 7 or month[4] != "-":
        raise HTTPException(status_code=400, detail="month must be YYYY-MM")
    master = await _resolve_salary_master_for_month(user["user_id"], cid, did, month)
    if not master:
        raise HTTPException(status_code=400, detail="No salary master effective for this month")
    from calendar import monthrange
    y, m = int(month[:4]), int(month[5:7])
    last_day = f"{month}-{monthrange(y, m)[1]:02d}"
    now = datetime.now(timezone.utc).isoformat()
    existing = await db.driver_ledger_entries.find_one({
        "user_id": user["user_id"], "company_id": cid, "driver_id": did,
        "entry_type": "salary", "source": "system",
        "reference.kind": "salary_master", "reference.month": month,
    })
    doc = {
        "user_id": user["user_id"], "company_id": cid, "driver_id": did,
        "entry_date": last_day,
        "month_key": month,
        "entry_type": "salary",
        "direction": "credit",
        "amount": round(float(master["monthly_salary"]), 2),
        "source": "system",
        "reference": {"kind": "salary_master", "id": master["id"], "month": month,
                       "version": master.get("version", 1)},
        "remarks": f"Monthly salary — {month}",
        "updated_at": now, "updated_by": user["user_id"],
    }
    if existing:
        await db.driver_ledger_entries.update_one({"_id": existing["_id"]}, {"$set": doc})
        eid = existing["id"]
    else:
        eid = new_id("dle")
        doc.update({"id": eid, "created_at": now, "created_by": user["user_id"]})
        await db.driver_ledger_entries.insert_one(doc)
    doc.pop("_id", None); doc.pop("user_id", None)
    await _log_audit(user, "driver_ledger", "post_monthly_salary", entity_id=eid, entity_ref=did,
                     changes={"month": month, "amount": doc["amount"]})
    return {**doc, "id": eid, "posted": not bool(existing), "updated": bool(existing)}


@router.post("/drivers/{did}/ledger/settle")
async def settle_month(did: str, payload: SettleIn, request: Request,
                        user=Depends(get_current_user)):
    """Record a monthly settlement payment.  Creates a debit entry dated
    the last day of `month`.  Idempotent — a second call for the same
    month replaces the previous settlement (or is deleted if paid=0).
    """
    cid = await _active_company_id(request, user)
    await _assert_driver(user["user_id"], cid, did)
    month = payload.month
    if len(month) != 7 or month[4] != "-":
        raise HTTPException(status_code=400, detail="month must be YYYY-MM")
    from calendar import monthrange
    y, m = int(month[:4]), int(month[5:7])
    last_day = f"{month}-{monthrange(y, m)[1]:02d}"
    now = datetime.now(timezone.utc).isoformat()
    existing = await db.driver_ledger_entries.find_one({
        "user_id": user["user_id"], "company_id": cid, "driver_id": did,
        "entry_type": "settlement", "source": "system",
        "reference.kind": "settlement", "reference.month": month,
    })
    if payload.paid_amount <= 0:
        # user is clearing the settlement — remove it if present
        if existing:
            await db.driver_ledger_entries.delete_one({"_id": existing["_id"]})
        return {"ok": True, "cleared": True, "month": month}
    doc = {
        "user_id": user["user_id"], "company_id": cid, "driver_id": did,
        "entry_date": last_day,
        "month_key": month,
        "entry_type": "settlement",
        "direction": "debit",
        "amount": round(float(payload.paid_amount), 2),
        "source": "system",
        "reference": {"kind": "settlement", "month": month},
        "remarks": (payload.remarks or "").strip() or f"Monthly settlement — {month}",
        "updated_at": now, "updated_by": user["user_id"],
    }
    if existing:
        await db.driver_ledger_entries.update_one({"_id": existing["_id"]}, {"$set": doc})
        eid = existing["id"]
    else:
        eid = new_id("dle")
        doc.update({"id": eid, "created_at": now, "created_by": user["user_id"]})
        await db.driver_ledger_entries.insert_one(doc)
    doc.pop("_id", None); doc.pop("user_id", None)
    await _log_audit(user, "driver_ledger", "settle", entity_id=eid, entity_ref=did,
                     changes={"month": month, "paid_amount": doc["amount"]})
    return {**doc, "id": eid}


# ===========================================================================
# Trip → Ledger Sync (called from routers/trips.py)
# ===========================================================================
async def sync_trip_recovery_to_ledger(user_id: str, cid: str, trip: dict) -> None:
    """Upsert a trip_recovery ledger entry mirroring the Trip's
    driver_recovery.final_recovery_amount.  Called on Trip create + update.

    Idempotent — reference={kind:'trip', id:tid} is the natural key.
    If recovery ≤ 0 (or no driver / no snapshot), any prior entry is
    removed (Trip is the single source of truth).
    """
    tid = trip.get("id")
    did = trip.get("driver_id")
    dr = trip.get("driver_recovery") or {}
    amount = float(dr.get("final_recovery_amount") or 0)
    key = {"user_id": user_id, "company_id": cid,
           "entry_type": "trip_recovery", "source": "system",
           "reference.kind": "trip", "reference.id": tid}
    if not did or amount <= 0:
        # Remove any orphaned entry (e.g. driver reassigned, override reduced to 0)
        await db.driver_ledger_entries.delete_many(key)
        return
    now = datetime.now(timezone.utc).isoformat()
    entry_date = trip.get("date") or datetime.now(timezone.utc).date().isoformat()
    doc = {
        "user_id": user_id, "company_id": cid, "driver_id": did,
        "entry_date": entry_date,
        "month_key": _month_key(entry_date),
        "entry_type": "trip_recovery",
        "direction": "debit",
        "amount": round(amount, 2),
        "source": "system",
        "reference": {
            "kind": "trip", "id": tid,
            "lr_number": trip.get("lr_number") or "",
            "vehicle_number": trip.get("vehicle_number") or "",
        },
        "remarks": f"Trip recovery — LR {trip.get('lr_number') or tid[:8]}",
        "updated_at": now,
    }
    existing = await db.driver_ledger_entries.find_one(key)
    if existing:
        # Preserve driver_id changes too — if driver reassigned, we must
        # remove the OLD driver's entry and insert a fresh one under the
        # new driver.
        if existing.get("driver_id") != did:
            await db.driver_ledger_entries.delete_one({"_id": existing["_id"]})
        else:
            await db.driver_ledger_entries.update_one({"_id": existing["_id"]}, {"$set": doc})
            return
    doc.update({"id": new_id("dle"), "created_at": now})
    await db.driver_ledger_entries.insert_one(doc)


async def delete_trip_recovery_from_ledger(user_id: str, cid: str, trip_id: str) -> None:
    """Delete the ledger entry linked to a Trip when the Trip is deleted."""
    await db.driver_ledger_entries.delete_many({
        "user_id": user_id, "company_id": cid,
        "entry_type": "trip_recovery", "source": "system",
        "reference.kind": "trip", "reference.id": trip_id,
    })


# ===========================================================================
# Monthly rollup (for Ledger UI header) + Export (CSV / PDF)
# ===========================================================================
@router.get("/drivers/{did}/ledger/monthly")
async def monthly_rollup(did: str, request: Request, user=Depends(get_current_user),
                          months: int = 12):
    """Return the last `months` months of activity rolled up:
    salary earned, advances, trip recoveries, other deductions,
    other payments, settlements, net + closing balance at month end.
    """
    cid = await _active_company_id(request, user)
    await _assert_driver(user["user_id"], cid, did)
    months = min(max(1, int(months or 12)), 36)
    pipeline = [
        {"$match": {"user_id": user["user_id"], "company_id": cid, "driver_id": did}},
        {"$group": {
            "_id": {"month": "$month_key", "type": "$entry_type", "dir": "$direction"},
            "total": {"$sum": "$amount"},
        }},
    ]
    buckets: dict = {}
    async for row in db.driver_ledger_entries.aggregate(pipeline):
        m = row["_id"]["month"] or ""
        b = buckets.setdefault(m, {"month": m, "salary": 0, "advance": 0,
                                    "other_payment": 0, "trip_recovery": 0,
                                    "other_deduction": 0, "settlement": 0,
                                    "credit_total": 0, "debit_total": 0})
        b[row["_id"]["type"]] = b.get(row["_id"]["type"], 0) + float(row["total"])
        if row["_id"]["dir"] == "credit":
            b["credit_total"] += float(row["total"])
        else:
            b["debit_total"] += float(row["total"])
    rows = sorted(buckets.values(), key=lambda r: r["month"], reverse=True)[:months]
    # Round + add net per month (credit - debit)
    for r in rows:
        for k in ("salary", "advance", "other_payment", "trip_recovery",
                  "other_deduction", "settlement", "credit_total", "debit_total"):
            r[k] = round(float(r.get(k, 0)), 2)
        r["net_change"] = round(r["credit_total"] - r["debit_total"], 2)
    return {"items": rows}


@router.get("/drivers/{did}/ledger/export")
async def export_ledger(did: str, request: Request, user=Depends(get_current_user),
                        format: str = "csv", date_from: str = "", date_to: str = ""):
    """Export the driver ledger as CSV or PDF."""
    fmt = (format or "csv").lower()
    if fmt not in ("csv", "pdf"):
        raise HTTPException(status_code=400, detail="format must be 'csv' or 'pdf'")
    cid = await _active_company_id(request, user)
    drv = await _assert_driver(user["user_id"], cid, did)
    opening = await _compute_opening_balance(user["user_id"], cid, did, date_from) if date_from else 0.0
    entries = await _list_entries(user["user_id"], cid, did, date_from, date_to)
    entries_with_bal, closing, credit_sum, debit_sum = _compute_running_balance(entries, opening)
    company = await db.companies.find_one(
        {"id": cid, "user_id": user["user_id"]}, {"_id": 0}) or {}

    fname = f"driver-ledger-{drv['name'].replace(' ', '_')}-{(date_from or 'all')}_to_{(date_to or 'now')}"

    if fmt == "csv":
        buf = io.StringIO()
        w = csv.writer(buf)
        w.writerow([f"Driver Ledger — {drv['name']}"])
        w.writerow([f"Company: {company.get('name','')}",
                    f"Period: {date_from or '—'}  to  {date_to or '—'}",
                    f"Opening Balance: {opening:.2f}"])
        w.writerow([])
        w.writerow(["Date", "Type", "Direction", "Amount", "Reference", "Remarks", "Running Balance"])
        for e in entries_with_bal:
            ref = e.get("reference") or {}
            ref_str = ""
            if ref.get("kind") == "trip":
                ref_str = f"Trip {ref.get('lr_number') or ref.get('id','')[:8]}"
            elif ref.get("kind") == "salary_master":
                ref_str = f"Salary {ref.get('month','')}"
            elif ref.get("kind") == "settlement":
                ref_str = f"Settlement {ref.get('month','')}"
            w.writerow([
                e["entry_date"], e["entry_type"], e["direction"],
                f"{e['amount']:.2f}", ref_str, e.get("remarks") or "",
                f"{e['balance']:.2f}",
            ])
        w.writerow([])
        w.writerow(["Total Credit", f"{credit_sum:.2f}"])
        w.writerow(["Total Debit", f"{debit_sum:.2f}"])
        w.writerow(["Closing Balance", f"{closing:.2f}"])
        return StreamingResponse(
            io.BytesIO(buf.getvalue().encode("utf-8-sig")),
            media_type="text/csv",
            headers={"Content-Disposition": f'attachment; filename="{fname}.csv"'},
        )
    # ---- PDF ----
    pdf_bytes = _build_ledger_pdf(company, drv, entries_with_bal,
                                   opening, closing, credit_sum, debit_sum,
                                   date_from, date_to)
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'inline; filename="{fname}.pdf"'},
    )


def _build_ledger_pdf(company: dict, driver: dict, entries: list,
                       opening: float, closing: float,
                       credit_sum: float, debit_sum: float,
                       date_from: str, date_to: str) -> bytes:
    from io import BytesIO
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Table, TableStyle, Spacer,
    )
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=12*mm, rightMargin=12*mm, topMargin=10*mm, bottomMargin=10*mm,
        title=f"Driver Ledger — {driver.get('name','')}",
    )
    styles = getSampleStyleSheet()
    story = []
    C_INK = colors.HexColor("#0F172A")
    C_MUTED = colors.HexColor("#64748B")
    C_LINE = colors.HexColor("#E2E8F0")
    C_ACCENT = colors.HexColor("#0EA5E9")
    C_CREDIT = colors.HexColor("#059669")
    C_DEBIT = colors.HexColor("#DC2626")

    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=14,
                        textColor=C_INK, spaceAfter=4)
    small = ParagraphStyle("small", parent=styles["Normal"], fontSize=9,
                           textColor=C_MUTED)
    story.append(Paragraph(f"<b>{company.get('name','—')}</b>", h1))
    story.append(Paragraph(
        f"Driver Ledger — <b>{driver.get('name','')}</b> "
        f"({driver.get('phone','—')})  ·  "
        f"Period: {date_from or '—'} to {date_to or '—'}", small))
    story.append(Spacer(1, 6))

    summary = [
        ["Opening Balance", f"₹ {opening:,.2f}"],
        ["Total Credit (Salary earned)", f"₹ {credit_sum:,.2f}"],
        ["Total Debit (Paid / Deducted)", f"₹ {debit_sum:,.2f}"],
        ["Closing Balance", f"₹ {closing:,.2f}"],
    ]
    t = Table(summary, colWidths=[70*mm, 40*mm])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("TEXTCOLOR", (0,0), (0,-1), C_MUTED),
        ("TEXTCOLOR", (1,-1), (1,-1), C_ACCENT),
        ("FONTNAME", (1,-1), (1,-1), "Helvetica-Bold"),
        ("LINEBELOW", (0,0), (-1,-2), 0.25, C_LINE),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
        ("TOPPADDING", (0,0), (-1,-1), 3),
    ]))
    story.append(t)
    story.append(Spacer(1, 8))

    # Entries table
    header = ["Date", "Type", "Reference", "Remarks", "Credit", "Debit", "Balance"]
    rows = [header]
    for e in entries:
        ref = e.get("reference") or {}
        ref_str = ""
        if ref.get("kind") == "trip":
            ref_str = f"Trip {ref.get('lr_number') or ref.get('id','')[:8]}"
        elif ref.get("kind") == "salary_master":
            ref_str = f"Salary {ref.get('month','')}"
        elif ref.get("kind") == "settlement":
            ref_str = f"Settlement {ref.get('month','')}"
        rows.append([
            e["entry_date"],
            e["entry_type"].replace("_", " ").title(),
            ref_str,
            (e.get("remarks") or "")[:40],
            f"{e['amount']:.2f}" if e["direction"] == "credit" else "",
            f"{e['amount']:.2f}" if e["direction"] == "debit" else "",
            f"{e['balance']:.2f}",
        ])
    if len(rows) == 1:
        rows.append(["—", "No entries", "", "", "", "", ""])
    tbl = Table(rows, colWidths=[22*mm, 25*mm, 30*mm, 44*mm, 20*mm, 20*mm, 25*mm], repeatRows=1)
    tbl.setStyle(TableStyle([
        ("FONTSIZE", (0,0), (-1,-1), 8),
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#F1F5F9")),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("TEXTCOLOR", (0,0), (-1,0), C_INK),
        ("LINEBELOW", (0,0), (-1,0), 0.5, C_LINE),
        ("LINEBELOW", (0,1), (-1,-1), 0.15, C_LINE),
        ("TEXTCOLOR", (4,1), (4,-1), C_CREDIT),
        ("TEXTCOLOR", (5,1), (5,-1), C_DEBIT),
        ("ALIGN", (4,1), (6,-1), "RIGHT"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
        ("TOPPADDING", (0,0), (-1,-1), 3),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        "<font color='#64748B' size='7'>Generated by Bitumen Transport Accounting — Driver Ledger. "
        "Credit = Salary Earned · Debit = Paid or Deducted · Balance = Running amount owed to driver.</font>",
        styles["Normal"]))
    doc.build(story)
    return buf.getvalue()
