"""Gate 9d · generate backend-node/src/python-route-table.ts from the REAL Python app.

Starlette's Router tries `app.routes` in order: the first FULL match (path +
method) handles the request; otherwise the first PARTIAL match (path only)
answers 405 with `Allow: ", ".join(route.methods)`; otherwise the path with its
trailing slash toggled is tried against every route (FULL or PARTIAL) for a
307; otherwise 404. Node needs that exact ordered table to reproduce the
framework edge. This script dumps it; it never touches business data.

Regex translation (Python `re` → JS, no `u` flag):
  (?P<name>…)  → (?<name>…)
  .*           → [^\\n]*      (Python `.` excludes only \\n; JS also \\r \\u2028 \\u2029)
  trailing $   → (?=\\n?$)     (Python `$` also matches before a final \\n)
Usage: python gen_python_route_table.py   (env MONGO_URL / DB_NAME only for import)
"""
import json, os, re, sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "backend"))
os.chdir(REPO / "backend")
os.environ.setdefault("MONGO_URL", "mongodb://localhost:27017")
os.environ.setdefault("DB_NAME", "trukvia_route_table_unused")
import server  # noqa: E402


def to_js(pattern: str) -> str:
    assert pattern.startswith("^") and pattern.endswith("$"), pattern
    js = pattern[:-1] + r"(?=\n?$)"
    js = js.replace("(?P<", "(?<")
    js = js.replace(">.*)", r">[^\n]*)")
    assert ".*" not in js, js
    return js


rows = []
for r in server.app.routes:
    methods = sorted(r.methods) if getattr(r, "methods", None) else None
    if methods is not None and len(methods) > 1:
        # Only Starlette's docs routes (GET+HEAD); Allow order is hash-seed dependent there.
        pass
    rows.append({"path": r.path, "re": to_js(r.path_regex.pattern), "methods": methods})

out = REPO / "backend-node" / "src" / "python-route-table.ts"
body = ",\n".join(
    "  [" + json.dumps(x["re"]) + ", " + json.dumps(x["methods"]) + ", " + json.dumps(x["path"][1:]) + "]" for x in rows)
out.write_text(
    "/**\n"
    " * GENERATED by backend-node/test/gate9d_parity/gen_python_route_table.py — do not edit.\n"
    " *\n"
    " * The Python app's routes in Starlette dispatch ORDER: [js regex source,\n"
    " * methods (null = any), path template WITHOUT its leading slash]. Used only\n"
    " * by http-edge.ts to reproduce Starlette's 405 / 307 / 404 framework\n"
    " * decisions. These are NOT route registrations: templates are stored\n"
    " * slash-less so the Phase-3 allowlist guard (quoted `/api/...` literals in\n"
    " * src/) keeps meaning \"Fastify routes Node registers\".\n"
    f" * Routes: {len(rows)}.\n"
    " */\n"
    "export const PYTHON_ROUTES: ReadonlyArray<readonly [string, readonly string[] | null, string]> = [\n"
    + body + ",\n];\n",
    encoding="utf-8", newline="\n")
print(f"wrote {out} ({len(rows)} routes)")
