"""Iter122 · All-Copies LR ZIP endpoint.

Verifies that `GET /api/trips/{tid}/lr/all-copies` returns a ZIP with exactly
three PDFs — one for each carriage copy (Original / Duplicate / Triplicate) —
generated by the SAME already-approved build_lr_pdf renderer from Iter115.

Contract:
  · 200 + application/zip
  · ZIP contains exactly 3 members, all *.pdf, starting with '%PDF' bytes
  · File names embed the LR number and the copy suffix
  · Uses the standard "assign lr_number if missing" behaviour (parity with
    single-copy /lr endpoint), never overwrites an existing lr_number
  · Does NOT mutate freight, shortage, supplier or invoice fields
"""
import io
import os
import zipfile
import requests

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "http://localhost:8001").rstrip("/")
API = f"{BASE_URL}/api"
TOKEN = "test_session_bitumen_2026"
HEADERS = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}


def _first_customer():
    r = requests.get(f"{API}/customers", headers=HEADERS, timeout=10)
    r.raise_for_status()
    return r.json()[0]["id"]


def _mk_trip():
    cid = _first_customer()
    r = requests.post(f"{API}/trips", headers=HEADERS, json={
        "customer_id": cid,
        "date": "2028-05-11",
        "vehicle_number": "AP99IT122A",
        "vehicle_type": "own",
        "tons": 20,
        "loaded_qty": 20,
        "unloaded_qty": 19.9,
        "freight_mode": "per_ton",
        "rate_per_ton": 900,
        "product_rate_per_mt": 40000,
        "from_location": "Kakinada",
        "to_location": "Vizag",
    }, timeout=30)
    r.raise_for_status()
    return r.json()["id"]


def test_all_copies_zip_returns_three_pdfs():
    tid = _mk_trip()
    r = requests.get(f"{API}/trips/{tid}/lr/all-copies", headers=HEADERS, timeout=60)
    assert r.status_code == 200, r.text
    assert r.headers.get("content-type", "").startswith("application/zip")
    zf = zipfile.ZipFile(io.BytesIO(r.content))
    names = zf.namelist()
    assert len(names) == 3, f"Expected 3 PDFs, got {len(names)}: {names}"
    suffixes = sorted(n.rsplit("_", 1)[-1].replace(".pdf", "").upper() for n in names)
    assert suffixes == ["DUPLICATE", "ORIGINAL", "TRIPLICATE"], suffixes
    for n in names:
        data = zf.read(n)
        assert data.startswith(b"%PDF"), f"{n} not a valid PDF"
        assert len(data) > 2000, f"{n} suspiciously small ({len(data)} bytes)"


def test_all_copies_zip_filename_carries_lr_number():
    tid = _mk_trip()
    r = requests.get(f"{API}/trips/{tid}/lr/all-copies", headers=HEADERS, timeout=60)
    assert r.status_code == 200
    disp = r.headers.get("content-disposition", "")
    assert "attachment" in disp
    assert "_all_copies.zip" in disp


def test_all_copies_zip_missing_trip_returns_404():
    r = requests.get(f"{API}/trips/does-not-exist-xyz/lr/all-copies", headers=HEADERS, timeout=10)
    assert r.status_code == 404


def test_all_copies_zip_does_not_mutate_business_fields():
    """The endpoint must be a pure renderer — freight, shortage, supplier and
    invoice fields must be byte-identical before and after."""
    tid = _mk_trip()
    before = requests.get(f"{API}/trips/{tid}", headers=HEADERS, timeout=10).json()
    r = requests.get(f"{API}/trips/{tid}/lr/all-copies", headers=HEADERS, timeout=60)
    assert r.status_code == 200
    after = requests.get(f"{API}/trips/{tid}", headers=HEADERS, timeout=10).json()
    for k in ("freight_amount", "total_expense", "profit", "supplier_freight",
              "supplier_shortage_deduction", "supplier_net_payable",
              "shortage_amount", "shortage_qty_mt", "invoice_id", "status"):
        assert before.get(k) == after.get(k), f"field {k} mutated: {before.get(k)} → {after.get(k)}"
