"""Iter143 P1 · Vehicle Workspace · Trip Cost tab — regression tests.

The Trip Cost tab is a PURE projection of:
  * GET /api/vehicles/{vid}/cost-summary  (authoritative cost source)
  * GET /api/trips?vehicle_id=vid          (metadata join)

Zero new backend endpoint. Zero schema change. Zero new collection.
Zero recalculation from Trip.total_expense / VendorBill / MechanicWO /
supplier payable.

Every assertion below mirrors an invariant the frontend depends on:

  1.  cost-summary row shape stable (trip_id, category, amount, source_type)
  2.  legacy XOR fallback rows still tagged & carry trip_id
  3.  supplier_freight / advance / diesel / net_payable NEVER appear in rows[]
  4.  supplier trip cost rows are visible with correct vehicle_id / vehicle_type
  5.  cancelled Quick Op vanishes from rows[]
  6.  reversed Expense excluded from rows[]
  7.  a zero-cost trip is invisible on the tab (no row generated by the FE)
  8.  cross-vehicle isolation (no leak)
  9.  date/category filter parity: cost-summary filter response == what the tab consumes
 10. sum of grouped trip totals == cost-summary.trip_linked_total
 11. trip_linked_total + non_trip_total == total_cost
 12. legacy → canonical materialisation preserves the same trip total
 13. non-trip Expense (trip_id="") never lands in any trip group

Frontend static guards confirm the tab is wired with the expected testids
and does NOT read from any of the forbidden legacy scalars.
"""
from pathlib import Path
import os
import uuid
import requests

BASE_URL = os.environ.get("REACT_APP_BACKEND_URL", "http://localhost:8001").rstrip("/")
API = f"{BASE_URL}/api"
if not API.startswith("http"):
    API = "http://localhost:8001/api"
TOKEN = os.environ.get("DEMO_TOKEN_VALUE", "")
H = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}


# ── Helpers ────────────────────────────────────────────────────────────────

def _customer():
    r = requests.get(f"{API}/customers", headers=H, timeout=15)
    for c in r.json():
        if c["name"] == "TEST_Iter143":
            return c["id"]
    return requests.post(
        f"{API}/customers", headers=H,
        json={"name": "TEST_Iter143", "state": "Andhra Pradesh"}, timeout=15,
    ).json()["id"]


def _first_own_vehicle():
    lst = requests.get(f"{API}/vehicles", headers=H, params={"active_only": True}, timeout=15).json()
    for v in lst:
        if (v.get("vehicle_type") or "").lower() != "supplier":
            return v
    return lst[0]


def _first_supplier_vehicle():
    lst = requests.get(f"{API}/vehicles", headers=H, params={"active_only": True}, timeout=15).json()
    for v in lst:
        if (v.get("vehicle_type") or "").lower() == "supplier":
            return v
    return None


def _mk_vendor(prefix="I143"):
    r = requests.post(
        f"{API}/vendors", headers=H,
        json={"name": f"{prefix}-{uuid.uuid4().hex[:6]}"}, timeout=15,
    )
    assert r.status_code in (200, 201), r.text
    return r.json()


def _create_own_trip(cid, veh, date="2028-03-01", tons=10):
    body = {
        "customer_id": cid, "date": date,
        "vehicle_number": veh["vehicle_number"],
        "vehicle_id": veh["id"],
        "vehicle_type": "own",
        "tons": tons, "freight_mode": "per_ton", "rate_per_ton": 1000,
        "from_location": "VJA", "to_location": "KKD",
        "driver_name": "I143 Driver",
    }
    r = requests.post(f"{API}/trips", headers=H, json=body, timeout=15)
    assert r.status_code == 200, r.text
    return r.json()


def _create_trip_with_legacy_expenses(cid, veh, date="2028-03-02"):
    """Bridge will materialise these → has_canonical_expenses=true."""
    body = {
        "customer_id": cid, "date": date,
        "vehicle_number": veh["vehicle_number"],
        "vehicle_id": veh["id"],
        "vehicle_type": "own",
        "tons": 10, "freight_mode": "per_ton", "rate_per_ton": 1000,
        "from_location": "VJA", "to_location": "KKD",
        "expenses": {"diesel": 8000, "toll": 1200, "batta": 500},
    }
    r = requests.post(f"{API}/trips", headers=H, json=body, timeout=15)
    assert r.status_code == 200, r.text
    return r.json()


def _post_expense_for_trip(veh_id, trip_id, category="Diesel", amount=5000.0,
                           date="2028-03-01"):
    body = {
        "date": date, "category": category, "amount": amount,
        "vehicle_id": veh_id, "trip_id": trip_id, "party_type": "cash",
        "settlement_mode": "cash_now", "narration": "iter143",
    }
    r = requests.post(f"{API}/expenses", headers=H, json=body, timeout=15)
    assert r.status_code in (200, 201), r.text
    return r.json()


def _cost_summary(veh_id, params=None):
    r = requests.get(f"{API}/vehicles/{veh_id}/cost-summary", headers=H,
                     params=params or {}, timeout=15)
    assert r.status_code == 200, r.text
    return r.json()


def _group_trip_costs(rows):
    """Mirror the frontend TripCostTab grouping — exact same rule."""
    groups = {}
    for r in rows:
        tid = r.get("trip_id")
        if not tid:
            continue
        if r.get("repair_event_id"):
            continue
        g = groups.setdefault(tid, {"total": 0.0, "categories": {}})
        amt = float(r.get("amount") or 0)
        g["total"] = round(g["total"] + amt, 2)
        c = r.get("category") or "Other"
        g["categories"][c] = round(g["categories"].get(c, 0.0) + amt, 2)
    return {tid: g for tid, g in groups.items() if g["total"] > 0}


# ── Backend guards ─────────────────────────────────────────────────────────

def test_cost_summary_row_shape_supports_tab():
    """Every row that the tab consumes must expose trip_id, category, amount,
    source_type (canonical or legacy_trip_fallback)."""
    veh = _first_own_vehicle()
    d = _cost_summary(veh["id"])
    for r in d["rows"]:
        assert "trip_id" in r
        assert "category" in r
        assert "amount" in r
        assert "source_type" in r


def test_supplier_payable_never_in_cost_rows():
    """supplier_freight / advance / diesel / net_payable are payable-side —
    NEVER show up as an Expense row."""
    veh = _first_own_vehicle()
    d = _cost_summary(veh["id"])
    for r in d["rows"]:
        # Neither the row itself nor any of its keys should reference the
        # supplier payable ledger.
        assert "supplier_freight" not in r
        assert "supplier_advance" not in r
        assert "supplier_diesel" not in r
        assert "supplier_net_payable" not in r


def test_grouping_matches_trip_linked_total_and_hides_zero():
    """SUM(grouped trip totals) MUST == cost-summary.trip_linked_total.
    Also verifies zero-cost trips do not surface (filter of total > 0)."""
    veh = _first_own_vehicle()
    d = _cost_summary(veh["id"])
    groups = _group_trip_costs(d["rows"])
    total = round(sum(g["total"] for g in groups.values()), 2)
    assert abs(total - float(d["trip_linked_total"])) < 0.01, (
        f"Displayed trip totals ({total}) must reconcile with "
        f"cost-summary.trip_linked_total ({d['trip_linked_total']})"
    )
    for tid, g in groups.items():
        assert g["total"] > 0, f"Zero-cost trip {tid} must be filtered by the tab"


def test_reconciliation_identity_trip_plus_nontrip_equals_total():
    """Trip-linked + Non-trip = Vehicle Total — the footer identity."""
    veh = _first_own_vehicle()
    d = _cost_summary(veh["id"])
    lhs = round(float(d["trip_linked_total"]) + float(d["non_trip_total"]), 2)
    rhs = round(float(d["total_cost"]), 2)
    assert abs(lhs - rhs) < 0.01, f"{lhs} != {rhs}"


def test_non_trip_row_never_grouped_into_any_trip():
    """A row with trip_id='' must never be attributed to any trip."""
    veh = _first_own_vehicle()
    d = _cost_summary(veh["id"])
    for r in d["rows"]:
        if not r.get("trip_id"):
            # By construction our grouping helper drops these — assert their
            # existence keeps them out of the trip map.
            groups = _group_trip_costs([r])
            assert groups == {}


def test_repair_linked_row_not_in_trip_cost_group():
    """Repair-linked expenses live on the Repairs tab, not Trip Cost."""
    veh = _first_own_vehicle()
    d = _cost_summary(veh["id"])
    fabricated = [
        r for r in d["rows"] if r.get("trip_id") and r.get("repair_event_id")
    ]
    groups = _group_trip_costs(fabricated)
    assert groups == {}, "Repair-linked rows must be excluded from Trip Cost"


def test_end_to_end_new_trip_with_expense_reflects_on_tab():
    """Create trip → post an Expense linked to it → group appears + total OK."""
    cid = _customer()
    veh = _first_own_vehicle()
    trip = _create_own_trip(cid, veh, date="2028-03-05")
    exp = _post_expense_for_trip(veh["id"], trip["id"], category="Diesel",
                                 amount=1234.50, date="2028-03-05")

    d = _cost_summary(veh["id"], {"from": "2028-03-05", "to": "2028-03-05"})
    groups = _group_trip_costs(d["rows"])
    assert trip["id"] in groups
    assert abs(groups[trip["id"]]["total"] - 1234.50) < 0.01
    assert "Diesel" in groups[trip["id"]]["categories"]

    # Reconciliation still holds.
    assert abs(sum(g["total"] for g in groups.values())
               - float(d["trip_linked_total"])) < 0.01

    # Cleanup
    requests.delete(f"{API}/expenses/{exp['id']}", headers=H,
                    params={"reason": "iter143 cleanup"}, timeout=15)


def test_cancelled_trip_expense_disappears_from_group():
    cid = _customer()
    veh = _first_own_vehicle()
    trip = _create_own_trip(cid, veh, date="2028-03-06")
    exp = _post_expense_for_trip(veh["id"], trip["id"], amount=999.0,
                                 date="2028-03-06")
    d1 = _cost_summary(veh["id"], {"from": "2028-03-06", "to": "2028-03-06"})
    g1 = _group_trip_costs(d1["rows"])
    assert trip["id"] in g1 and abs(g1[trip["id"]]["total"] - 999.0) < 0.01

    requests.delete(f"{API}/expenses/{exp['id']}", headers=H,
                    params={"reason": "iter143 cancel"}, timeout=15)

    d2 = _cost_summary(veh["id"], {"from": "2028-03-06", "to": "2028-03-06"})
    g2 = _group_trip_costs(d2["rows"])
    # Trip total drops (or trip disappears entirely if this was its only cost)
    assert g2.get(trip["id"], {}).get("total", 0) == 0, (
        "Cancelled Expense must NOT leave a residual cost on its trip"
    )


def test_legacy_only_trip_shows_via_xor_fallback():
    """A trip with legacy scalars materialises canonical rows via the bridge.
    Whether canonical or fallback, the tab sees exactly ONE contribution
    per legacy line (never both)."""
    cid = _customer()
    veh = _first_own_vehicle()
    trip = _create_trip_with_legacy_expenses(cid, veh, date="2028-03-07")

    d = _cost_summary(veh["id"], {"from": "2028-03-07", "to": "2028-03-07"})
    groups = _group_trip_costs(d["rows"])
    assert trip["id"] in groups
    expected = 8000 + 1200 + 500
    assert abs(groups[trip["id"]]["total"] - expected) < 0.01, (
        f"legacy trip total {groups[trip['id']]['total']} != expected {expected}"
    )

    # Every row for this trip must have exactly one source flag; and we must
    # never see BOTH a canonical row and a legacy fallback row for the same
    # (trip, category).
    seen = {}
    for r in d["rows"]:
        if r.get("trip_id") != trip["id"]:
            continue
        key = (r["category"], r.get("source_type"))
        seen.setdefault(key, 0)
        seen[key] += 1
    # No double-counting: canonical + legacy_fallback for same category → banned
    for cat in ("Diesel", "Toll", "Batta"):
        canonical = sum(v for (c, s), v in seen.items()
                        if c == cat and s != "legacy_trip_fallback")
        fallback = sum(v for (c, s), v in seen.items()
                       if c == cat and s == "legacy_trip_fallback")
        assert not (canonical > 0 and fallback > 0), (
            f"XOR violated: both canonical and legacy fallback for {cat}"
        )


def test_supplier_trip_visible_and_payable_not_summed():
    """If the tenant has a supplier vehicle, a trip on it must be groupable
    (cost-side only) and its supplier payable fields must remain out of the
    cost sum."""
    sup = _first_supplier_vehicle()
    if not sup:
        return  # tenant has no supplier vehicle — skip
    cid = _customer()
    body = {
        "customer_id": cid, "date": "2028-03-08",
        "vehicle_number": sup["vehicle_number"],
        "vehicle_id": sup["id"],
        "vehicle_type": "supplier",
        "supplier_id": sup.get("supplier_id") or "",
        "supplier_name": sup.get("supplier_name") or "",
        "tons": 10, "freight_mode": "per_ton", "rate_per_ton": 1000,
        "supplier_freight_mode": "per_ton",
        "supplier_rate_per_ton": 800,
        "supplier_advance": 3000,          # payable side — must NOT count as cost
        "supplier_diesel": 2000,           # payable side — must NOT count as cost
        "from_location": "VJA", "to_location": "KKD",
    }
    r = requests.post(f"{API}/trips", headers=H, json=body, timeout=15)
    if r.status_code != 200:
        # Supplier trip creation may be blocked by tenant policy — skip.
        return
    trip = r.json()

    # Post one real cost row on this trip.
    _post_expense_for_trip(sup["id"], trip["id"], category="Toll",
                           amount=150.0, date="2028-03-08")
    d = _cost_summary(sup["id"], {"from": "2028-03-08", "to": "2028-03-08"})
    groups = _group_trip_costs(d["rows"])
    if trip["id"] in groups:
        # Only the real Toll cost is counted; supplier_advance / diesel absent.
        assert abs(groups[trip["id"]]["total"] - 150.0) < 0.01, (
            f"Supplier-payable leaked into cost: got {groups[trip['id']]['total']}"
        )


def test_cross_vehicle_isolation():
    """Cost-summary for vehicle A must never contain a row whose vehicle_id
    is vehicle B."""
    veh = _first_own_vehicle()
    d = _cost_summary(veh["id"])
    for r in d["rows"]:
        # Row may carry vehicle_id="" for very old fallback trips; when set,
        # it MUST match the queried vehicle.
        if r.get("vehicle_id"):
            assert r["vehicle_id"] == veh["id"], (
                f"cross-vehicle leak: got row vid={r.get('vehicle_id')} != {veh['id']}"
            )


def test_from_to_filter_parity_with_cost_summary():
    """Filtering by from/to via the same cost-summary must produce a subset
    of the unfiltered result. The tab reuses these exact params — parity."""
    veh = _first_own_vehicle()
    unfiltered = _cost_summary(veh["id"])
    if unfiltered["expense_count"] == 0:
        return
    filtered = _cost_summary(veh["id"], {"from": "2099-01-01", "to": "2099-01-02"})
    assert filtered["expense_count"] == 0, (
        "Far-future range must return zero rows (filter must be respected)"
    )
    assert filtered["total_cost"] == 0


def test_category_filter_parity_with_cost_summary():
    veh = _first_own_vehicle()
    d = _cost_summary(veh["id"], {"category": "Diesel"})
    for r in d["rows"]:
        assert r["category"] == "Diesel", (
            f"category filter breach — got {r['category']}"
        )


# ── Frontend static guards ─────────────────────────────────────────────────

FRONTEND_PATH = Path("/app/frontend/src/pages/VehicleWorkspace.jsx")


def test_frontend_trip_cost_tab_present_and_wired():
    src = FRONTEND_PATH.read_text(encoding="utf-8")
    for m in [
        # Tab wiring
        '{ id: "trip-cost", label: "Trip Cost" }',
        # Test IDs
        'data-testid="vw-trip-cost"',
        'data-testid="vw-trip-cost-total"',
        'data-testid="vw-trip-cost-reconciled"',
        'data-testid="vw-trip-cost-empty"',
        'data-testid={`vw-trip-cost-row-${idx}`}',
        # Component wiring
        'function TripCostTab',
        'function TripCostRow',
        # Data source reuse — MUST use cost-summary rows + /api/trips only
        '/vehicles/${vid}/cost-summary',
        'api.get("/trips"',
        # Grouping key
        'trip_id',
        # Reconciliation footer wording
        'Trip-linked Costs',
        'Non-trip Costs',
        'Vehicle Total',
    ]:
        assert m in src, f"VehicleWorkspace.jsx missing marker: {m}"


def test_frontend_trip_cost_tab_does_not_use_forbidden_scalars():
    """Trip Cost tab must not project cost from any forbidden source
    (Trip.total_expense, Trip.expenses scalars, VendorBill/MechanicWO
    amounts, supplier payable fields)."""
    src = FRONTEND_PATH.read_text(encoding="utf-8")
    # Find the TripCostTab function body up to its closing brace.
    idx = src.index("function TripCostTab")
    end = src.index("function TripCostRow", idx)
    body = src[idx:end]
    forbidden = [
        "total_expense",
        "supplier_freight",
        "supplier_advance",
        "supplier_diesel",
        "supplier_net_payable",
        "vendor_bills",
        "mechanic_work_orders",
        "bill_amount",
    ]
    for f in forbidden:
        assert f not in body, (
            f"TripCostTab body references forbidden field '{f}' — must project"
            " from cost-summary.rows[] only"
        )


def test_frontend_tab_placement_between_expenses_and_repairs():
    src = FRONTEND_PATH.read_text(encoding="utf-8")
    order_snippet = src[src.index("id: \"overview\""):src.index("id: \"reports\"")]
    # Enforce the mandated ordering.
    p_over = order_snippet.index('"overview"')
    p_exp = order_snippet.index('"expenses"')
    p_trip = order_snippet.index('"trip-cost"')
    p_rep = order_snippet.index('"repairs"')
    assert p_over < p_exp < p_trip < p_rep, "Tab order must be Overview | Expenses | Trip Cost | Repairs | Reports"


def test_frontend_no_new_backend_endpoint_call():
    """No accidental call to a not-yet-built /trip-costs endpoint."""
    src = FRONTEND_PATH.read_text(encoding="utf-8")
    assert "/trip-costs" not in src, (
        "Iter143 P1 must NOT call /api/vehicles/{vid}/trip-costs — that is P2"
    )
