// Iter55 — Extracted from TripForm.jsx. Pure defaults + shared input CSS.
// DO NOT ADD LOGIC HERE. Keep this file identical to the original const/values.

export const EMPTY = {
  customer_id: "",
  ship_site_id: "",                 // Iter66 · Phase B
  customer_reference_number: "",    // Iter66 · Phase B
  date: new Date().toISOString().slice(0, 10),
  vehicle_number: "",
  vehicle_id: "",
  vehicle_type: "own",
  supplier_id: "",
  supplier_name: "",
  supplier_freight: 0,
  supplier_freight_mode: "per_ton",
  supplier_rate_per_ton: 0,
  supplier_fixed_amount: 0,
  supplier_round_trip_kms: 0,
  supplier_rate_per_km_per_ton: 0,
  supplier_loading_point: "",
  supplier_unloading_point: "",
  supplier_material: "",
  supplier_quantity: 0,
  supplier_advance: 0,
  supplier_diesel: 0,
  supplier_shortage_deduction: 0,
  supplier_shortage_deduction_override: false,
  supplier_other_recoveries: 0,
  supplier_other_income: 0,
  supplier_net_payable: 0,
  driver_id: "",
  driver_name: "",
  driver_mobile: "",
  product_id: "",
  load_details: "Bitumen VG 40",
  hsn_sac: "",
  tons: 0,
  from_location: "",
  to_location: "",
  from_pincode: "",
  to_pincode: "",
  freight_mode: "per_ton",
  rate_per_ton: 0,
  fixed_amount: 0,
  round_trip_kms: 0,
  rate_per_km_per_ton: 0,
  // Loading / Unloading tracking
  loading_date: "",
  unloading_date: "",
  loaded_qty: 0,
  unloaded_qty: 0,
  shortage_qty: 0,
  excess_qty: 0,
  product_rate_per_mt: 0,
  shortage_amount: 0,
  excess_amount: 0,
  shortage_amount_override: false,
  excess_amount_override: false,
  // Halting / Waiting charges
  total_halting_days: 0,
  grace_days: 4,
  chargeable_halting_days: 0,
  halting_rate_per_day: 0,
  halting_amount: 0,
  halting_amount_override: false,
  expenses: {
    diesel: 0, toll: 0, batta: 0, repair: 0, other: 0,
    firewood: 0, other_desc: "",
    diesel_from_customer_qty: 0, diesel_from_customer_rate: 0, diesel_from_customer_amount: 0,
    shortage_qty: 0, shortage_amount: 0, cash_advance_received: 0,
  },
  notes: "",
  lr_number: "",
  lr_time: "",
  consignor_name: "",
  consignor_address: "",
  consignee_site_location: "",
  consignee_site_contact: "",
  external_invoice_no: "",
  customer_invoice_no: "",
  customer_purchased_at: "",
  invoice_value: 0,
  waybill_no: "",
  gross_weight: 0,
  tare_weight: 0,
  seal_numbers: "",
  other_expenditures: [],
  halting_remarks: "",
  shortage_remarks: "",
  excess_remarks: "",
  other_income: 0,
  other_income_remarks: "",
  supplier_settlement_remarks: "",
  lr_driver_name: "",
  lr_driver_mobile: "",
  customer_diesel_received: 0,
  customer_advance_received: 0,
  customer_receipts: [],
};

// Iter75 — bumped mobile tap targets: py-2.5 → min-h ~40px inputs. text-base
// on mobile prevents iOS zoom-on-focus.
export const inputCls = "w-full border border-zinc-300 px-3 py-2.5 rounded-sm text-base sm:text-sm min-h-[40px] focus:border-zinc-950 focus:ring-1 focus:ring-zinc-950 outline-none bg-white";
